' Gambas module file

Source As String[] = Split(File.load("puzzle"), "\n", "", True)
MathStack As New SnailNumber[]

Public Sub Main()

  Print "Hello world"
  
  For Each s As String In source
    Dim TempNum As New SnailNumber(s)
    MathStack.push(TempNum)
  Next
  
  Dim Accumulator As SnailNumber = MathStack[0]
  For i As Integer = 1 To MathStack.Max
    Accumulator = Accumulator.Add(MathStack[i], True)
  Next
  
  'Accumulator.PrettyPrint()
  'Print "Left  Side";; Accumulator.Left._print()
  'Print "Right Side";; Accumulator.Right._print()
  Print "Part 1 Magnitude         = "; Accumulator.Magnitude
  Print "Part 2 Largest Magnitude = "; FindLargestMagnitude()
End

Sub FindLargestMagnitude() As Long

  Dim Largest As Long = 0
  For Each sn As Snailnumber In MathStack
    For Each sn2 As SnailNumber In MathStack
      If sn <> sn2 Then
        Dim Accum As SnailNumber = sn.Add(sn2)
        If Accum.Magnitude > Largest Then Largest = Accum.Magnitude
        Accum = sn2.Add(sn)
        If Accum.Magnitude > Largest Then Largest = Accum.Magnitude
      Endif
    Next
  Next
  Return Largest
End

